spring:
  application:
    name: demo
  ai:
    chat:
      client:
        observations:
          log-prompt: true
      observations:
        log-completion: true
        log-prompt: true
    ollama:
      init:
        pull-model-strategy: when_missing
      chat:
        options:
          model: granite3.3:2b
          temperature: 0.7
      embedding:
        options:
          model: granite-embedding:278m
    vectorstore:
      observations:
        log-query-response: true
      mongodb:
        initialize-schema: true
